parameters:
    sylius.form.type.cart.validation_groups: ['toro_currency']

sylius_grid:
    grids:
        sylius_admin_currency:
            fields:
                name:
                    type: twig
                    label: sylius.ui.name
                    path: .
                    options:
                        template: '@ToroShopCurrency/Currency/Grid/Field/name.html.twig'

        sylius_admin_exchange_rate:
            fields:
                sourceCurrency:
                    type: twig
                    label: sylius.ui.source_currency
                    path: .
                    options:
                        template: "@ToroShopCurrency/ExchangeRate/Grid/Field/sourceCurrencyName.html.twig"
                targetCurrency:
                    type: twig
                    label: sylius.ui.target_currency
                    path: .
                    options:
                        template: "@ToroShopCurrency/ExchangeRate/Grid/Field/targetCurrencyName.html.twig"
