sylius_admin_product_option:
    resource: |
        alias: sylius.product_option
        section: admin
        templates: SyliusAdminBundle:Crud
        except: ['show']
        redirect: update
        grid: sylius_admin_product_option
        permission: true
        form:
            options:
                option_type: $type
        vars:
          all:
              subheader: sylius.ui.manage_configuration_options_of_your_products
              templates:
                  form: ToroShopCoreBundle:ProductOption:_form.html.twig
          create:
              route:
                  name: sylius_admin_product_option_create
                  parameters:
                      type: $type
          index:
              icon: options
    type: sylius.resource
