imports:
     - { resource: "@ToroShopAddressBundle/Resources/config/grid/main.yml" }
     - { resource: "./sylius_resource.yml" }

jms_serializer:
    metadata:
        directories:
            toro_address:
                namespace_prefix: "ToroShop\\Bundle\\AddressBundle"
                path: "@ToroShopAddressBundle/Resources/config/serializer"
sylius_grid:
    templates:
        filter:
            geo_tree: '@ToroShopAddress/Admin/Sylius/Grid/Filter/geo.html.twig'
