winzou_state_machine:
    sylius_order:
        callbacks:
            after:
                sylius_save_addresses_on_customer:
                    on: ["create"]
                    do: ["@toro_shop_core.resolver.order_address_resolver", "resolve"]
                    args: ["object"]
